### ISSUE TITLE
Complies but no file "smdk-usbdl" generated

### ISSUE THREAD

**Issue by seno30** [astarasikov/exynos9610-edl-mode#1]
when i press make it enters into directories and exits, it compiles but still i cant see the file 'smdk-usbdl". 

Does this work on "exynos 9611" m30s device. Ive bricked it and now it doesnt boot into download mode nor recovery mode tried all possible key combinations but none worked so maybe this will work hopefully.  Do i have to just run the program and plug in my device?  Im willing to experiment with the device as the samsung guys said to replace motherboard, I flashed wrong twrp and this happened. Im sure the official samsung worker said to replace motherboard just for making money,

**Comment by astarasikov** [comment]
Hi, please edit the makefile and remove "xcrun" if you're building on Linux
and not on Mac.

Does your device get recognized on USB? As 1234:04e8. If not, it could be a
hardware issue and it might be easier to go to the official service centre
(I also had my device bricked during a fw update, but they could not even
bring it to the 1234 mode and replaced the motherboard for free. However,
if the device does turn on in any mode and then they find out that KNOX is
tripped/the device [not A50, but S10] is unlocked (which was not the case
for mine, it had stock FW), they'll charge $50).

I am not sure this will work out of the box. It might be necessary to
confirm that offsets within the s-boot.bin are the same on exynos9611 as on
exynos9610, but it's likely that it can work without any changes.

**Comment by seno30** [comment]
hello
the file compiled and was able to run the tool but it says "failed to find device". Im just connecting the usb cable  from my phone to the pc without removing anything. What do you mean by "Does your device get recognized on USB? As 1234:04e8" and yes i went to service center the guy straight away said to replace a new motherboard which he said my device voids warranty because he saw the message that my bootloader is unlocked. im trying to fix my device maybe your tool will work

**Comment by astarasikov** [comment]
Your device should get detected when you plug it into PC. In the emergency recovery mode the USB Vendor ID should be 04e8 and Product ID should be 1234.
If it's not getting recognized as a USB device, you should continue trying button combinations to enter the bootloader or try to find a schematic so that you can force entering emergency mode by shortening some pin on the PCB.
It could also be that there is hardware damage.
Unfortunately this is hard to diagnose remotely and I'm not sure I can help much.
